OLED_ENABLE = yes
ENCODER_ENABLE = yes
CONSOLE_ENABLE = yes
EXTRAKEY_ENABLE = yes
VIA_ENABLE = yes
VIAL_ENABLE = yes
ENCODER_MAP_ENABLE = yes
LTO_ENABLE = yes
QMK_SETTINGS = no
MOUSEKEY_ENABLE = yes
COMBO_ENABLE = no
KEY_OVERRIDE_ENABLE = no
RGBLIGHT_ENABLE = yes
TAP_DANCE_ENABLE = no
BACKLIGHT_ENABLE = no
WPM_ENABLE = yes

# RP2040 specific settings
ifeq ($(strip $(CONVERT_TO)), rp2040_ce)
    VIAL_INSECURE = yes
    VIAL_TAP_DANCE_ENTRIES = 32
    VIAL_COMBO_ENTRIES = 32
    VIAL_KEY_OVERRIDE_ENTRIES = 32
endif